### ISSUE TITLE
a error when i install pyautogui that indepened python-lib

### ISSUE THREAD

**Issue by Linkding** [alexer/python-xlib#2]
##### issu：install pyautogui fail
- OS：centos6.4
- pyhton：2.7.1
-  known：i have Source Installaed  python-xlib successed（to python2）     ----------or python3-xlib(to python3)

> result：
> [root@lin PyAutoGUI-0.9.33]# python setup.py install
> Traceback (most recent call last):
>   File "setup.py", line 6, in <module>
>     version=**import**('pyautogui').**version**,
>   File "/usr/PyAutoGUI-0.9.33/pyautogui/**init**.py", line 114, in <module>
>     from . import _pyautogui_x11 as platformModule
>   File "/usr/PyAutoGUI-0.9.33/pyautogui/_pyautogui_x11.py", line 153, in <module>
>     _display = Display(None) # TODO - Display() can have other values passed to it. Implement that later.
>   File "/usr/local/lib/python2.7/site-packages/Xlib/display.py", line 83, in __init__
>     self.display = _BaseDisplay(display)
>   File "/usr/local/lib/python2.7/site-packages/Xlib/display.py", line 65, in __init__
>     apply(protocol.display.Display.**init**, (self, ) + args, keys)
>   File "/usr/local/lib/python2.7/site-packages/Xlib/protocol/display.py", line 44, in **init**
>     name, host, displayno, screenno = connect.get_display(display)
>   File "/usr/local/lib/python2.7/site-packages/Xlib/support/connect.py", line 65, in get_display
>     return mod.get_display(display)
>   File "/usr/local/lib/python2.7/site-packages/Xlib/support/unix_connect.py", line 59, in get_display
>     raise error.DisplayNameError(display)
> Xlib.error.DisplayNameError: Bad display name ""

how to fix it.

**Comment by qiujieqiong** [comment]
#python2
sudo apt-get install python-pip
sudo pip install pyautogui
pip show pyautogui
#python3
sudo apt-get install python3-pip
sudo pip3 install pyautogui
pip3 show pyautogui

**Comment by ranarieliU** [comment]
I'm having same issue on python3 and this doesn't work for me.
Any suggestions?

**Comment by qiujieqiong** [comment]
check if exist ".Xauthority" in your root dir, only /home/user exist ".Xauthority", so change your authority to user : su - user

**Comment by studioj** [comment]
I had the same problem when installing pyautogui via SSH. When i opened the commandline tool on screen of the device itself and ran  pip install pyautogui everything worked like a charm...

**Comment by qiujieqiong** [comment]
You need 'export DISPLAY=:0' before 'pip install pyautogui ' if you install pyautogui via SSH.

**Comment by Alexhha** [comment]
Or you can use xvfb-run pip install pyautogui
